{% set name = "cattrs" %}
{% set version = "23.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cattrs-{{ version }}.tar.gz
  sha256: db1c821b8c537382b2c7c66678c3790091ca0275ac486c76f3c8f3920e83c657

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - python >=3.7
    - pip
    - poetry-core >=1.1.0
  run:
    - python >=3.7
    - attrs >=20
    # only for py<3.11 but we want to stay noarch
    - typing_extensions >=4.1.0
    # only for py<3.11 but we want to stay noarch
    - exceptiongroup

test:
  imports:
    - cattr
    - cattr.preconf
  requires:
    - pip
  commands:
    - pip check

  ### These tests could be added if we switch to getting the package from
  ### GitHub, not pypi

  # requires:
  #   - pytest
  #   - hypothesis
  # commands:
  #   - py.test -v tests
  # source_files:
  #   - tests

about:
  home: https://github.com/python-attrs/cattrs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Complex custom class converters for attrs.
  description: |
    cattrs is an open source Python library for structuring and unstructuring data.
    cattrs works best with attrs classes and the usual Python collections, but other
    kinds of classes are supported by manually registering converters.

    PyPI: [https://pypi.org/project/cattrs](https://pypi.org/project/cattrs)

  doc_url: https://cattrs.readthedocs.io/en/latest/
  dev_url: https://github.com/python-attrs/cattrs

extra:
  recipe-maintainers:
    - aldanor
    - Tinche
    - xylar
    - sugatoray
