{% set name = "cattrs" %}
{% set version = "1.8.0" %}
{% set sha256 = "5c121ab06a7cac494813c228721a7feb5a6423b17316eeaebf13f5a03e5b0d53" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7
    - attrs >=20

test:
  imports:
    - cattr
    - cattr.converters
  requires:
    - pip
  commands:
    - pip check

  ### These tests could be added if we switch to getting the package from
  ### GitHub, not pypi

  # requires:
  #   - pytest
  #   - hypothesis
  # commands:
  #   - py.test -v tests
  # source_files:
  #   - tests

about:
  home: https://github.com/Tinche/cattrs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Complex custom class converters for attrs.
  description: |
    cattrs is an open source Python library for structuring and unstructuring data.
    cattrs works best with attrs classes and the usual Python collections, but other
    kinds of classes are supported by manually registering converters.
  doc_url: https://cattrs.readthedocs.io/en/latest/
  dev_url: https://github.com/Tinche/cattrs

extra:
  recipe-maintainers:
    - aldanor
    - Tinche
    - xylar
