{% set name = "cattrs" %}
{% set version = "24.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cattrs-{{ version }}.tar.gz
  sha256: 981a6ef05875b5bb0c7fb68885546186d306f10f0f6718fe9b96c226e68821ff

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python


requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - typing_extensions >=4.1.0,!=4.6.3
    - python >={{ python_min }}
    - attrs >=23.1.0
    # only for py<3.11 but we want to stay noarch
    - typing-extensions >=4.1.0,!=4.6.3
    # only for py<3.11 but we want to stay noarch
    - exceptiongroup >=1.1.1

test:
  imports:
    - cattr
    - cattr.preconf
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

  ### These tests could be added if we switch to getting the package from
  ### GitHub, not pypi

  # requires:
  #   - pytest
  #   - hypothesis
  # commands:
  #   - py.test -v tests
  # source_files:
  #   - tests

about:
  home: https://github.com/python-attrs/cattrs
  summary: Composable complex class support for attrs and dataclasses.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    cattrs is an open source Python library for structuring and unstructuring data.
    cattrs works best with attrs classes and the usual Python collections, but other
    kinds of classes are supported by manually registering converters.

    PyPI: [https://pypi.org/project/cattrs](https://pypi.org/project/cattrs)

  doc_url: https://cattrs.readthedocs.io/en/latest/
  dev_url: https://github.com/python-attrs/cattrs

extra:
  recipe-maintainers:
    - aldanor
    - Tinche
    - xylar
    - sugatoray
