{% set name = "cattrs" %}
{% set version = "0.9.0" %}
{% set sha256 = "2232a568e079f30601de63839f4101283cb594c8719f5311bede25f89d0e09b7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python >=3.5,<3.8
    - pip
    - attrs >=17.3
  run:
    - python >=3.5,<3.8
    - attrs >=17.3

test:
  imports:
    - cattr
    - cattr.converters

  ### Lines below can be uncommented if/when tests stop using relative imports and
  ### instead import from the installed package like they're supposed to.

  # requires:
  #   - pytest
  #   - hypothesis
  # commands:
  #   - py.test -v tests
  # source_files:
  #   - tests

about:
  home: https://github.com/Tinche/cattrs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Complex custom class converters for attrs.'
  description: |
    cattrs is an open source Python library for structuring and unstructuring data.
    cattrs works best with attrs classes and the usual Python collections, but other
    kinds of classes are supported by manually registering converters.
  doc_url: https://cattrs.readthedocs.io/en/latest/
  dev_url: https://github.com/Tinche/cattrs

extra:
  recipe-maintainers:
    - aldanor
    - Tinche
    - xylar
