travis:
  secure:
    BINSTAR_TOKEN: YrTHR/3uvtI6JD7J63RrhXYDVYbnzYli8Ntrg07sBbTqIUPQznAQ7LhZ0wIO6A/Rd4+dJcO5jXEmiH34JNhSIre0I4lCcrxAjOAtqHKRpfukewPf1mwpUUXFcEy0W/OAetm16sXBncp37ZSgOUPSj8tPc+/dXfDFAaoEuQLWYt+JauAHoFG+SwgOMIJhStiRN0uwKnWLbaf5PRmA90390a6T4s2sFtkyQP92LMgEtdh1QpIpTMzxHPufO2DcD8JGSBu7mu0vY1IVGFfQhQ0QIXf4G+eCwXhp+Gw4iOUFt6NuZ40tkMQsT+Hc3JgYJEhwwPd1AJ5/CyhdgFfkk0buWyjabh/hn6ZXqFCKZUkwPeMZWs9+2HiMWAqGA0Arp/J+E280xmsQhAO6Sf0dccG0GwM3btaWjtjfcbwgH4eSbZQh+lsaBznw56tfi+wp9Fp4LfTtRg6yF51VcC+Omk7ydOC2KY9HbjY+5DmRrFHmNG5tcStWCDFN2Eh9rI1woliFRw3y0UmK8w/+VFvwRm9fVhd7XC7UheQUASupPDaV52043A1XQsRAq++d8Vzg0I3QYhhNMnMbqsx1pUyzDwYaNbjVDLSX+aUxEjc9DAS5cUCfdvfNgKnJsWh4fg9Nc/eBU2cLRHQadZBJ0tci8t1pol4PA9rzwIXRwY7O3T+5x9o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
